language: c

compiler:
  - gcc
  - clang

sudo: false

before_install:
    - pip install --user urllib3[secure]
    - pip install --user cpp-coveralls

script:
    - make test

after_success:
    - coveralls --gcov-options '\-lp'

