.TH icarus 1 icarus


.SH NAME
Icarus - Programming language (and implementation) designed as an experiment to explore mutation and aliasing control


.SH SYNOPSIS
.B icarus
[\fI\,COMMAND\/\fR]
[\fI\,OPTIONS\/\fR]


.SH COPYRIGHT AND LICENSE
.B Icarus
is Copyright (C) 2015-2016 Chris Hall
.br
.B Icarus
is released under the terms of the MIT license


.SH COMMAND

.IR check
.br
.RS
perform static analysis on input file
.RE
.P

.IR transform
.br
.RS
transform input file
.RE
.P

.IR 2c
.br
.RS
run 2c - compiles icarus code to C
.RE
.P

.IR pancake
.br
.RS
run pancake - the icarus interpreter
.RE
.P

.IR <default>
.br
.RS
defaults to `pancake` if a command is omitted
.RE
.P


.SH OPTIONS

.IR debug
.br
.RS
enable icarus internal debug output
.RE
.P

.IR help,     -h
.br
.RS
print this help message
.RE
.P

.IR input,
-i
.I file
.br
.RS
input filename
.RE
.P

.IR output,
-o
.I file
.br
.RS
output filename
.RE
.P

.IR version
.br
.RS
print version of icarus
.RE
.P

.IR <default>
.br
.RS
an argument will default to being an `input` file if the preceding option is omitted
.RE
.P


.SH EXAMPLES

.TP
icarus foo.ic
run file `foo.ic` through `pancake`

.TP
icarus check --input foo.ic
perform static analysis on file `foo.ic`

.TP
icarus 2c -i foo.ic -o foo.c
compile `foo.ic` to c and output that in new file `foo.c`

.TP
icarus pancake foo.ic --debug
run `foo.ic` through pancake with debug output

.TP
icarus -h
print this help page


.SH AUTHORS
Chris Hall
<followingthepath at gmail d0t com>


.SH BUGS
All bug reports for
.B Icarus
should either be reported on github at https://github.com/mkfifo/icarus or emailed to the author(s)


.SH SOURCE
The source code for
.B Icarus
can be found on github at https://github.com/mkfifo/icarus


